export const CHOOSE_COUNTRY = 'CHOOSE_COUNTRY';
export const CHOOSE_CATEGORY = 'CHOOSE_CATEGORY';
export const INPUT_QUERY = 'INPUT_QUERY';
export const SET_DATE = 'SET_DATE';
export const LOAD_NEWS = 'LOAD_NEWS';

export const LOAD_DISPLAY_ON = 'LOAD_DISPLAY_ON';
export const LOAD_DISPLAY_OFF = 'LOAD_DISPLAY_OFF';

export const LOAD_CURRENCY_RATES = 'LOAD_CURRENCY_RATES';

export const GET_LOCALSTORAGE_DATA = 'GET_LOCALSTORAGE_DATA';
export const SET_LOCALSTORAGE_DATA = 'SET_LOCALSTORAGE_DATA';

export const LOAD_WEATHER = 'LOAD_WEATHER';

export const GET_CONFIGURATIONS = 'GET_CONFIGURATIONS';
export const SET_CONFIGURATIONS = 'SET_CONFIGURATIONS';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_PASSWORD = 'EDIT_PASSWORD';
export const SUBSCRIBE = 'SUBSCRIBE';
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const EDIT_SUBSCRIPTIONS = 'EDIT_SUBSCRIPTIONS';
export const DELETE_SUBSCRIPTIONS = 'DELETE_SUBSCRIPTIONS';
